// <auto-generated />
namespace Projects.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tbl_current_stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tbl_current_stock));
        
        string IMigrationMetadata.Id
        {
            get { return "201706030519318_tbl_current_stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
